sudo: required
services:
    - docker

before_install:
    - docker build -t p7bala/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true p7bala/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "Docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-west-2-931792372181"
    bucket_path: "Docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"    

    
